#!/bin/bash

# Generate RSA key pair
openssl genpkey -algorithm RSA -out school.key -aes256 -pass pass:betty -pkeyopt rsa_keygen_bits:4096

# Extract the public key
openssl rsa -pubout -in school -out school.pub
